export default {
  '1': {
    id: 1,
    src: `${BUCKET_URL}${HIDEAWAY_ASSETS.stickers.sticker1}`,
    width: 513 / 4,
    height: 272 / 4,
  },
  '2': {
    id: 2,
    src: `${BUCKET_URL}${HIDEAWAY_ASSETS.stickers.sticker2}`,
    width: 196 / 2,
    height: 65 / 2,
  },
  '3': {
    id: 3,
    src: `${BUCKET_URL}${HIDEAWAY_ASSETS.stickers.sticker3}`,
    width: 80,
    height: 80,
  },
  '4': {
    id: 4,
    src: `${BUCKET_URL}${HIDEAWAY_ASSETS.stickers.sticker4}`,
    width: 174 / 2,
    height: 76 / 2,
  },
  '5': {
    id: 5,
    src: `${BUCKET_URL}${HIDEAWAY_ASSETS.stickers.sticker5}`,
    width: 80,
    height: 80,
  },
  '6': {
    id: 6,
    src: `${BUCKET_URL}${HIDEAWAY_ASSETS.stickers.sticker6}`,
    width: 80,
    height: 80,
  },
  '7': {
    id: 7,
    src: `${BUCKET_URL}${HIDEAWAY_ASSETS.stickers.sticker7}`,
    width: 254 / 3,
    height: 305 / 3,
  },
  '8': {
    id: 8,
    src: `${BUCKET_URL}${HIDEAWAY_ASSETS.stickers.sticker8}`,
    width: 350 / 3,
    height: 247 / 3,
  },
  '9': {
    id: 9,
    src: `${BUCKET_URL}${HIDEAWAY_ASSETS.stickers.sticker9}`,
    width: 186 / 2,
    height: 112 / 2,
  },
  '10': {
    id: 10,
    src: `${BUCKET_URL}${HIDEAWAY_ASSETS.stickers.sticker10}`,
    width: 423 / 3,
    height: 111 / 3,
  },
  '11': {
    id: 11,
    src: `${BUCKET_URL}${HIDEAWAY_ASSETS.stickers.sticker11}`,
    width: 100,
    height: 87,
  },
  '12': {
    id: 12,
    src: `${BUCKET_URL}${HIDEAWAY_ASSETS.stickers.sticker12}`,
    width: 199 / 2,
    height: 72 / 2,
  },
  '13': {
    id: 13,
    src: `${BUCKET_URL}${HIDEAWAY_ASSETS.stickers.sticker13}`,
    width: 288 / 3,
    height: 249 / 3,
  },
  '14': {
    id: 14,
    src: `${BUCKET_URL}${HIDEAWAY_ASSETS.stickers.sticker14}`,
    width: 102,
    height: 96,
  },
  '15': {
    id: 15,
    src: `${BUCKET_URL}${HIDEAWAY_ASSETS.stickers.sticker15}`,
    width: 186 / 2,
    height: 249 / 2,
  },
  '16': {
    id: 16,
    src: `${BUCKET_URL}${HIDEAWAY_ASSETS.stickers.sticker16}`,
    width: 172 / 2,
    height: 270 / 2,
  },
  '17': {
    id: 17,
    src: `${BUCKET_URL}${HIDEAWAY_ASSETS.stickers.sticker17}`,
    width: 301 / 3,
    height: 272 / 3,
  },
  '18': {
    id: 18,
    src: `${BUCKET_URL}${HIDEAWAY_ASSETS.stickers.sticker18}`,
    width: 353 / 4,
    height: 588 / 4,
  },
  '19': {
    id: 19,
    src: `${BUCKET_URL}${HIDEAWAY_ASSETS.stickers.sticker19}`,
    width: 178 / 2,
    height: 223 / 2,
  },
};
