import { degToRad } from '@hideaway/pages/poster/utils/rotations';
import preview from './2.jpg';
let stickerId = 0;
const Temp1: PosterData = {
  id: 'temp2',
  preview: preview,
  background: `${BUCKET_URL}${HIDEAWAY_ASSETS.templates[1].bg}`,
  desc: 'Embrace a fresh new world',
  subTitle: '扫码定制专属旅行手账，\n更有惊喜好礼等着你！',
  textfields: [
    {
      id: 1,
      content: `逸游茶境 赏景悦己\n旅行的意义是沉浸美景之中\n与更美好的自己不期而遇`,
      limit: 40,
      x: 18 + 152 * 0.5,
      y: 367 + 48 * 0.5,
      width: 152,
      height: 50,
      fontSize: 12,
      fontWeight: 'normal',
      rotation: 0,
      textAlign: 'left',
      color: '#323D47',
      lineHeight: 16,
    },
    {
      id: 4,
      content: '成都松弛之旅\nfresh’s\nPLOG',
      limit: 25,
      x: 294,
      y: 689,
      width: 62,
      height: 41,
      fontSize: 10,
      lineHeight: 11,
      fontWeight: '600',
      rotation: 12,
      textAlign: 'left',
      color: '#292726',
    },
  ],
  photos: [
    {
      id: 4,
      src: `${BUCKET_URL}${HIDEAWAY_ASSETS.templates[1].photo4}`,

      x: 115,
      y: 206,
      width: 226,
      height: 119,
      ratio: '16:9',
      rotation: -0.95,
      touched: false,
      status: 'success',
      zIndex: 1,
    },
    {
      id: 1,
      src: `${BUCKET_URL}${HIDEAWAY_ASSETS.templates[1].photo1}`,

      x: 282,
      y: 263,
      width: 158,
      height: 130,
      ratio: '5:4',
      rotation: 5.81,
      touched: false,
      status: 'success',
      zIndex: 2,
    },
    {
      id: 2,
      src: `${BUCKET_URL}${HIDEAWAY_ASSETS.templates[1].photo2}`,

      x: 267,
      y: 412,
      width: 158,
      height: 130,
      ratio: '5:4',
      rotation: 5.81,
      touched: false,
      status: 'success',
      zIndex: 3,
    },
    {
      id: 3,
      src: `${BUCKET_URL}${HIDEAWAY_ASSETS.templates[1].photo3}`,

      x: 115,
      y: 551,
      width: 233,
      ratio: '4:3',
      height: 160,
      rotation: -3.62,
      touched: false,
      status: 'success',

      zIndex: 4,
    },
  ],
  stickers: [
    {
      id: stickerId++,
      name: 'tb1',
      width: 112,
      height: 75,
      x: 226 + 112 * 0.5,
      y: 121 + 75 * 0.5,
      rotation: degToRad(0),
    },
    {
      id: stickerId++,
      name: 'tb3',
      width: 80,
      height: 48,
      x: 48,
      y: 303,
      rotation: degToRad(-2.42),
    },
    {
      id: stickerId++,
      name: 'tb7',
      width: 157,
      height: 43,
      y: 323 + 43 * 0.5,
      x: 5 + 157 * 0.5,
      rotation: degToRad(0),
    },
    {
      id: stickerId++,
      name: 'tb2',
      width: 83,
      height: 60,
      x: 60,
      y: 453,
      rotation: degToRad(3.93),
    },
    {
      id: stickerId++,
      name: 'charf.png',
      width: 33.11,
      height: 35.6,
      x: 250,
      y: 550,
      rotation: degToRad(-13.32),
    },
    {
      id: stickerId++,
      name: 'charr.png',
      width: 28.65,
      height: 38.84,
      x: 281,
      y: 546,
      rotation: degToRad(-13.32),
    },
    {
      id: stickerId++,
      name: 'chare.png',
      width: 28.65,
      height: 38.2,
      x: 311,
      y: 537,
      rotation: degToRad(-24.94),
    },
    {
      id: stickerId++,
      name: 'chares.png',
      width: 24.16,
      height: 27.23,
      x: 336,
      y: 529,
      rotation: degToRad(-8.51),
    },
    {
      id: stickerId++,
      name: 'charh.png',
      width: 21.32,
      height: 44.59,
      x: 355,
      y: 524,
      rotation: degToRad(0.72),
    },
  ],
};
export default Temp1;
