import { degToRad } from '@hideaway/pages/poster/utils/rotations';
import preview from './3.png';
import AllStickers from '../stickers';
const Temp1: PosterData = {
  id: 'tmp3',
  preview: preview,
  background: `${BUCKET_URL}${HIDEAWAY_ASSETS.templates[2].bg}`,
  desc: '这是模板3 的文字哈哈哈',
  textfields: [
    {
      id: 1,
      content: '仓木繁叶将热烈与喧嚣阻挡。',
      limit: 20,
      x: 93,
      y: 221,
      width: 72,
      height: 30,
      fontSize: 10,
      fontWeight: 'normal',
      rotation: 0,
      textAlign: 'left',
      color: 'black',
      lineHeight: 14,
    },

    {
      id: 2,
      content:
        '仓木繁叶将热烈与 喧嚣阻挡 无数生命在此蔓延生长 青苔在寂静、潮湿。仓木繁叶将热烈与 喧嚣阻挡 无数生命在此。仓木繁叶将热烈与 喧嚣阻挡 无数生命在此蔓延生长 青苔在寂静、潮湿。',
      limit: 100,
      x: 211,
      y: 255,
      width: 72,
      height: 122,
      fontSize: 8,
      fontWeight: 'normal',
      rotation: 0,
      textAlign: 'left',
      color: 'black',
      lineHeight: 11,
    },
    {
      id: 3,
      content:
        '仓木繁叶将热烈与 喧嚣阻挡 无数生命在此蔓延生长 青苔在寂静、潮湿。  仓木繁叶将热烈与 喧嚣阻挡 无数生命在此蔓延。',
      limit: 70,
      x: 306,
      y: 408,
      width: 100,
      height: 53,
      fontSize: 8,
      fontWeight: 'normal',
      rotation: 0,
      textAlign: 'left',
      color: 'black',
      lineHeight: 11,
    },
    {
      id: 4,
      content:
        '仓木繁叶将热烈与 喧嚣阻挡 无数生命在此蔓延生长 无数生命在此蔓延生无数生命在此蔓延生。仓木繁叶将热烈与 喧嚣阻挡 无数生命在此蔓延生长 无数生命在此蔓延生。',
      limit: 80,
      x: 86,
      y: 586,
      width: 128,
      height: 54,
      fontSize: 8,
      fontWeight: 'normal',
      rotation: 0,
      textAlign: 'left',
      color: 'white',
      lineHeight: 11,
    },
    {
      id: 5,
      content: '你分享的城市？\nby: fresh',
      limit: 20,
      x: 310,
      y: 748,
      width: 59,
      height: 45,
      fontSize: 13,
      fontWeight: 'bold',
      rotation: 26.52,
      textAlign: 'left',
      color: 'black',
      lineHeight: 15,
    },
  ],
  photos: [
    {
      id: 1,
      src: `${BUCKET_URL}${HIDEAWAY_ASSETS.templates[2].photo1}`,
      x: 96,
      y: 332,
      width: 147,
      height: 170,
      ratio: '4:5',
      rotation: -10.05,
      touched: false,
      status: 'success',
    },
    {
      id: 2,
      src: `${BUCKET_URL}${HIDEAWAY_ASSETS.templates[2].photo2}`,
      x: 316,
      y: 298,
      width: 116,
      height: 134,
      ratio: '4:5',
      rotation: 0,
      touched: false,
      status: 'success',
    },
    {
      id: 3,
      src: `${BUCKET_URL}${HIDEAWAY_ASSETS.templates[2].photo3}`,
      x: 276,
      y: 576,
      width: 199,
      height: 266,
      ratio: '3:4',
      rotation: 0,
      touched: false,
      status: 'success',
    },
  ],
  stickers: [
    {
      ...AllStickers[1],
      width: 256 / 3,
      height: 136 / 3,
      x: 110,
      y: 180,
      rotation: degToRad(-10),
    },
  ],
};
export default Temp1;
