import { degToRad } from '@hideaway/pages/poster/utils/rotations';
import preview from './1.png';

let stickerId = 0;
const Temp1: PosterData = {
  id: 'temp1',
  preview: preview,
  background: `${BUCKET_URL}${HIDEAWAY_ASSETS.templates[0].bg}`,
  desc: '这是模板1的文字',
  textfields: [
    {
      id: 5,
      content: `从繁忙的生活中抽离\n给自然来个大大拥抱\n唤醒肌肤光彩活力\n享受旅途美好时光`,
      limit: 50,
      x: 93,
      y: 472,
      width: 113,
      height: 71,
      fontSize: 12,
      fontWeight: 'normal',
      lineHeight: 16,
      rotation: 8.44,
      textAlign: 'center',
      color: '#292726',
    },
    {
      id: 7,
      content: `成都松弛之旅\nfresh’s PLOG`,
      limit: 25,
      x: 289,
      y: 688,
      width: 72,
      height: 30,
      fontSize: 11,
      fontWeight: 600,
      lineHeight: 14,
      rotation: 2.33,
      textAlign: 'left',
      color: '#292726',
    },
  ],
  photos: [
    {
      id: 1,
      src: `${BUCKET_URL}${HIDEAWAY_ASSETS.templates[0].photo1}`,

      x: 289,
      y: 346,
      width: 180,
      height: 180,
      rotation: 12,
      touched: false,
      status: 'success',
    },
    {
      id: 2,

      src: `${BUCKET_URL}${HIDEAWAY_ASSETS.templates[0].photo2}`,
      x: 271,
      y: 540,
      width: 122,
      height: 135,
      rotation: -4.58,
      touched: false,
      // status: 'invalid_content',
      status: 'success',
    },
    {
      id: 3,
      src: `${BUCKET_URL}${HIDEAWAY_ASSETS.templates[0].photo3}`,

      x: 95,
      y: 198,
      width: 162,
      height: 168,
      rotation: 6.2,
      touched: false,
      // status: 'in_check',
      status: 'success',
    },
  ],

  stickers: [
    {
      id: stickerId++,
      name: 'ta6',
      width: 69,
      height: 72,
      x: 244,
      y: 137,
      rotation: 0,
      // rotation: degToRad(-10),
    },
    {
      id: stickerId++,
      name: 'ta5',
      width: 57,
      height: 90,
      x: 301,
      y: 196,
      rotation: 0,
      // rotation: degToRad(-10),
    },
    {
      id: stickerId++,
      name: 'ta4',
      width: 80,
      height: 96,
      x: 201,
      y: 338,
      rotation: degToRad(15.33),
      // rotation: degToRad(-10),
    },
    {
      id: stickerId++,
      name: 'ta3',
      width: 83,
      height: 104,
      x: 23 + 83 * 0.5,
      y: 304 + 104 * 0.5,
      rotation: 0,
      // rotation: degToRad(-10),
    },
    {
      id: stickerId++,
      name: 'ta10',
      width: 35,
      height: 46,
      x: 142 + 35 * 0.5,
      y: 383 + 46 * 0.5,
      rotation: 0,
      // rotation: degToRad(-10),
    },
    {
      id: stickerId++,
      name: 'ta9',
      width: 65,
      height: 36,
      x: 191 + 65 * 0.5,
      y: 406 + 36 * 0.5,
      rotation: 0,
      // rotation: degToRad(-10),
    },
    {
      id: stickerId++,
      name: 'ta1',
      width: 106,
      height: 84,
      x: 66,
      y: 576,
      rotation: degToRad(-22.39),
      // rotation: degToRad(-10),
    },
    {
      id: stickerId++,
      name: 'tabs19',
      width: 111,
      height: 48,
      x: 120,
      y: 630,
      rotation: degToRad(-10.26),
      // rotation: degToRad(-10),
    },
    {
      id: stickerId++,
      name: 'ta2',
      width: 63,
      height: 56,
      x: 224,
      y: 674,
      rotation: degToRad(2.33),
      // rotation: degToRad(-10),
    },
    {
      id: stickerId++,
      name: 'takty.png',
      width: 115,
      height: 44,
      x: 96 + 115 / 2,
      y: 257 + 44 / 2,
      rotation: 0,
      // rotation: degToRad(-10),
    },

    // {
    //   id: stickerId++,
    //   name: 'ta6',
    //   width: 69,
    //   height: 72,
    //   x: 238,
    //   y: 203,
    //   rotation: 0,
    //   // rotation: degToRad(-10),
    // },
    // {
    //   id: stickerId++,
    //   name: 'ta11',
    //   width: 33,
    //   height: 28,
    //   x: 356,
    //   y: 183,
    //   rotation: degToRad(-22.3),
    // },

    // {
    //   id: stickerId++,
    //   name: 'ta5',
    //   width: 57,
    //   height: 89,
    //   x: 341,
    //   y: 241,
    //   rotation: 0,
    // },

    // {
    //   id: stickerId++,
    //   name: 'ta3',
    //   width: 76,
    //   height: 95,
    //   x: 91,
    //   y: 308,
    //   rotation: 0,
    // },

    // {
    //   id: stickerId++,
    //   name: 'ta12',
    //   width: 120,
    //   height: 105,
    //   x: 151,
    //   y: 391,
    //   rotation: 0,
    // },

    // {
    //   id: stickerId++,
    //   name: 'ta4',
    //   width: 85,
    //   height: 102,
    //   x: 37,
    //   y: 398,
    //   rotation: 0,
    // },
    // {
    //   id: stickerId++,
    //   name: 'ta1',
    //   width: 92,
    //   height: 73,
    //   x: 150,
    //   y: 559,
    //   rotation: 0,
    // },

    // {
    //   id: stickerId++,
    //   name: 'ta9',
    //   width: 75,
    //   height: 42,
    //   x: 311,
    //   y: 451,
    //   rotation: 0,
    // },

    // {
    //   id: stickerId++,
    //   name: 'ta7',
    //   width: 24,
    //   height: 26,
    //   x: 31,
    //   y: 623,
    //   rotation: degToRad(9.33),
    // },
    // {
    //   id: stickerId++,
    //   name: 'ta10',
    //   width: 35,
    //   height: 46,
    //   x: 29,
    //   y: 668,
    //   rotation: degToRad(-12),
    // },

    // {
    //   id: stickerId++,
    //   name: 'ta14',
    //   width: 60,
    //   height: 29,
    //   x: 196,
    //   y: 434,
    //   rotation: degToRad(-9.33),
    // },

    // {
    //   id: stickerId++,
    //   name: 'ta2',
    //   width: 63,
    //   height: 56,
    //   x: 212,
    //   y: 690,
    //   rotation: degToRad(-6.83),
    // },
    // {
    //   id: stickerId++,
    //   name: 'ta8',
    //   width: 68,
    //   height: 68,
    //   x: 43,
    //   y: 111,
    //   rotation: 0,
    // },
  ],
};
export default Temp1;
