import { degToRad } from '@hideaway/pages/poster/utils/rotations';
import preview from './2.png';
import AllStickers from '../stickers';
const Temp1: PosterData = {
  id: 'tmp2',
  preview: preview,
  background: `${BUCKET_URL}${HIDEAWAY_ASSETS.templates[1].bg}`,
  desc: '这是模板2 的文字',
  textfields: [
    {
      id: 1,
      content: '仓木繁叶将热烈与喧嚣阻挡\n无数生命在此蔓延生长\n喧嚣阻挡',
      limit: 30,
      x: 90,
      y: 332,
      width: 132,
      height: 50,
      fontSize: 11,
      fontWeight: 'normal',
      rotation: 0,
      textAlign: 'left',
      color: '#323D47',
      lineHeight: 16,
    },
    {
      id: 2,
      content:
        '仓木繁叶将热烈与喧嚣阻挡 无数生命在此蔓延生长 青苔在寂静、潮湿的空气中\n为大地盛开一片柔软湿凉\n微小又顽强的力量',
      limit: 100,
      x: 114,
      y: 437,
      width: 182,
      height: 60,
      fontSize: 9,
      fontWeight: '300',
      rotation: 0,
      textAlign: 'left',
      lineHeight: 15,
      color: '#292726',
    },
    {
      id: 3,
      content:
        '仓木繁叶将热烈与 喧嚣阻挡 无数\n生命在此蔓延生长 青苔在寂静、潮湿的空气中 仓木繁叶将热烈',
      limit: 30,
      x: 315,
      y: 560,
      width: 100,
      height: 85,
      fontSize: 10,
      lineHeight: 14,
      fontWeight: '300',
      rotation: 0,
      textAlign: 'left',
      color: '#000',
    },
    {
      id: 4,
      content: '你分享的\n城市？\nby: fresh',
      limit: 20,
      x: 300,
      y: 714,
      width: 72,
      height: 41,
      fontSize: 12,
      lineHeight: 14,
      fontWeight: '600',
      rotation: 12,
      textAlign: 'left',
      color: '#292726',
    },
  ],
  photos: [
    {
      id: 1,
      src: `${BUCKET_URL}${HIDEAWAY_ASSETS.templates[1].photo1}`,

      x: 291,
      y: 326,
      width: 134,
      height: 100,
      ratio: '5:4',
      rotation: 7,
      touched: false,
      status: 'success',
    },
    {
      id: 2,
      src: `${BUCKET_URL}${HIDEAWAY_ASSETS.templates[1].photo2}`,

      x: 276,
      y: 446,
      width: 134,
      height: 100,
      ratio: '5:4',
      rotation: 7,
      touched: false,
      status: 'success',
    },
    {
      id: 3,
      src: `${BUCKET_URL}${HIDEAWAY_ASSETS.templates[1].photo2}`,

      x: 121,
      y: 575,
      width: 231,
      ratio: '4:3',
      height: 157,
      rotation: -1.81,
      touched: false,
      status: 'success',
    },
  ],
  stickers: [],
};
export default Temp1;
